stages:
  - test
  - deploy

run_tests:
  stage: test
  image: python:3.6
  script:
    - pip install pipenv
    - pipenv install --deploy -d
    - pipenv run python tests.py
    - pipenv run flake8 --ignore= setup.py tests.py taguette
